# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
History.destroy_all
Madlib.destroy_all
# User.destroy_all

Madlib.reset_pk_sequence
History.reset_pk_sequence
# User.reset_pk_sequence

Madlib.create(chapter: "01", title: "Introduction to the Assignment", template: "Hello <name>! Your previous work has made you the best candidate to design a safety video for <company_name> on <company_activity>. <name>, you have been blessed with budget of <money_amount> for this project. We at <company_name> are looking <adverb> to the amazing video that you can produce for an introduction to safety on <company_activity>. Let us begin the journey <name>.", placeHolderEmpty: "{\"<name>\": \"\", \"<company_name>\": \"\", \"<company_activity>\": \"\", \"<money_amount>\": \"\", \"<adverb>\": \"\"}")
Madlib.create(chapter: "02", title: "To Pick a Team Member Part 1", template: "Welcome to the room of <room_name>, <name>. We have lined <adjective3> crew here at <company_name> for you to create a team of <adjective1> talent to help you produce the safety video. First up is <name1>, they have <verb1_past_tense> the work place for items that may be useful for you such as, <item1>, <item2>, and a <item3>. Second up is <name2>, who has been <adjective4> with the <office_appliance1> for days. It tells them of <adjective2> tales of past safety inspectors and how they have never <verb2> from inspecting <office_appliance2>. I will continue after a short <beverage> break.", placeHolderEmpty: "{\"<name>\": \"\", \"<name1>\": \"\", \"<name2>\": \"\",\"<room_name>\": \"\",\"<company_name>\": \"\",\"<adjective1>\": \"\",\"<adjective2>\": \"\",\"<adjective3>\": \"\",\"<adjective4>\": \"\",\"<verb1_past_tense>\": \"\",\"<verb2>\": \"\",\"<item1>\": \"\",\"<item2>\": \"\",\"<item3>\": \"\",\"<office_appliance1>\": \"\",\"<office_appliance2>\": \"\",\"<beverage>\": \"\"}")
Madlib.create(chapter: "03", title: "You Are Under Attack", template: "<name>! We have come under attack by the <adjective1> <enemy_group>. They are destroying our <building_name> with <adjective3>, using <adjective2> waves of <spell_name>. You must transform into your deep secret super power of <super_power_form>. Do not worry we have your great companion, <partner_name>, already on there way here to help you defeat <enemy_group>. They are even bringing your trusty <weapon_name> along with a sippy cup of the fabled <beverage> for when you need it.", placeHolderEmpty: "{\"<name>\": \"\", \"<enemy_group>\": \"\", \"<building_name>\": \"\",\"<spell_name>\": \"\",\"<super_power_form>\": \"\",\"<partner_name>\": \"\",\"<adjective1>\": \"\",\"<adjective2>\": \"\",\"<adjective3>\": \"\",\"<weapon_name>\": \"\",\"<beverage>\": \"\"}")
Madlib.create(chapter: "04", title: "But There is Traffic", template: "You have been <adverb_how_often_or_how> waiting at <company_name>’s office for your partner <partner_name>. Suddenly <name> rushes into the room you are waiting <adverb_how_often_or_how> at. We have just receive news that <partner_name> is stuck in <city_name>’s subway system. There has been a <mechanical_failure_or_disaster>, and the <city_name>’s repair crew will not be able to make it in time to save our <building_name>. It is <adjective> for us to help you find items here that are worthy to help defeat <enemy_group>.", placeHolderEmpty: "{\"<company_name>\": \"\", \"<partner_name>\": \"\", \"<name>\": \"\",\"<city_name>\": \"\",\"<mechanical_failure_or_disaster>\": \"\",\"<building_name>\": \"\",\"<enemy_group>\": \"\",\"<adverb>\": \"\",\"<adjective>\": \"\"}")
Madlib.create(chapter: "05", title: "The Search for a Weapon", template: "<name> is going to lead you to the <company_room>. Inside you will find items that may be worthy to help defeat the <enemy_group>. Once inside you are presented with table of items on display for you to pick. The first is a <office_appliance> of adjective1>, it has absolutely no power hidden inside. The second is a <kitchen_appliance> of <adjective2>, it has a faint glow only visible to your eyes. The third is a <bathroom_toy> of <adjective3>, it has the strongest glow and energy radiating from it to your eyes and the best choice to use to defeat <enemy_group>.", placeHolderEmpty: "{\"<name>\": \"\", \"<company_room>\": \"\", \"<enemy_group>\": \"\",\"<office_appliance>\": \"\",\"<kitchen_appliance>\": \"\",\"<bathroom_toy>\": \"\",\"adjective1>\": \"\",\"<adjective2>\": \"\",\"<adjective3>\": \"\"}")
